version: '3.8'

x-environment-defaults: &environment-defaults
  DEBUG: "False"
  DB_NAME: "coffee-db"
  DB_USER: "*****"
  DB_PASSWORD: "****!"
  DB_HOST: "postgres"
  DB_PORT: 5432
  TW_MAIL: "partners@***"
  TW_PASSWORD: "******!"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"

services:
  co:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: co
    environment:
      <<: *environment-defaults
    volumes:
      - ./co:/co
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - celery
    restart: on-failure:5
    networks:
      - coffee-network

  postgres:
    image: postgres:latest
    container_name: postgres_co
    environment:
      POSTGRES_DB: coffee-db
      POSTGRES_USER: ******
      POSTGRES_PASSWORD: *****!
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - coffee-network

  redis:
    image: redis:alpine
    container_name: redis_co
    ports:
      - "6380:6379"
    restart: on-failure:5
    networks:
      - coffee-network

  celery:
    build:
      context: .
    command: celery -A co worker --loglevel=info
    container_name: celery_co
    environment:
      <<: *environment-defaults
    depends_on:
      - redis
    volumes:
      - ./co:/co
    networks:
      - coffee-network

  nginx:
    image: nginx:1.23.3
    container_name: nginx_co
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
      - ./certbot/www:/var/www/certbot
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
      - "443:443"
    networks:
      - coffee-network
    depends_on:
      - co
    command: ["/bin/sh", "-c", "chown -R nginx:nginx /static && exec nginx -g 'daemon off;'"]


  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile.certbot
    container_name: certbot_co
    ports:
      - "6000:80"
    networks:
      - coffee-network
    volumes:
      - ./nginx/:/etc/nginx/
      - ./certbot/www:/var/www/certbot

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  coffee-network:
    driver: bridge