FROM nginx:latest


RUN apt-get update && apt-get install -y certbot python3-certbot-nginx && rm -rf /var/lib/apt/lists/*

COPY conf/nginx.conf /etc/nginx/nginx.conf 
COPY conf/startup.sh /startup.sh
RUN chmod +x /startup.sh

EXPOSE 80 443

#CMD ["/startup.sh"]