# Generated by Django 5.1.1 on 2024-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callme',
            name='message',
            field=models.TextField(max_length=900, null=True),
        ),
        migrations.DeleteModel(
            name='CallMeItem',
        ),
    ]
