# Generated by Django 5.1.1 on 2024-11-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_callme_message_delete_callmeitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callme',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='callme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='callme',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
